### ISSUE TITLE
Out of memory when using datasource-proxy-spring-boot-starter

### ISSUE THREAD

**Issue by nickcodefresh** [gavlyukovskiy/spring-boot-data-source-decorator#19]
When I include datasource-proxy-spring-boot-starter (v1.3.2) in my project I get an out of memory exception. When analysing it in MAT I see:

`
One instance of "java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue" loaded by "<system class loader>" occupies 84,915,400 (35.90%) bytes. The instance is referenced by net.ttddyy.dsproxy.listener.logging.SLF4JSlowQueryListener @ 0xef5be0d8 , loaded by "org.springframework.boot.loader.LaunchedURLClassLoader @ 0xed41b578". The memory is accumulated in one instance of "java.util.concurrent.RunnableScheduledFuture[]" loaded by "<system class loader>".
`
Any ideas why this might happen?

**Comment by gavlyukovskiy** [comment]
I assume this happens because datasource-proxy creates scheduled job for every query to log a warning if query was not ended within specified threshold. 
I think it is related to https://github.com/ttddyy/datasource-proxy/pull/53 which is already fixed in version 1.4.9, while starter brings version 1.4.5. Please try to override datasource-proxy to at least that version.
