### ISSUE TITLE
JDBC spans not made with Spring Cloud Finchley

### ISSUE THREAD

**Issue by shakuzen** [gavlyukovskiy/spring-boot-data-source-decorator#23]
I noticed that spans are not reported to Zipkin for any JDBC calls when using Finchley. Looking at the autoconfiguration's conditions, it still depends on the type `org.springframework.cloud.sleuth.Tracer` which does not exist in Sleuth 2 anymore.

https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/blob/ce050c16b3afda0e05a5e1cd53db8ab6e6847676/datasource-decorator-spring-boot-autoconfigure/src/main/java/com/github/gavlyukovskiy/cloud/sleuth/SleuthListenerAutoConfiguration.java#L29

If the plan is to support only Spring Boot 2 / Spring Cloud Finchley in the 1.4.x line, it's probably best to update the Sleuth version compiled against to at least `2.0.0.RELEASE`.

https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/blob/ce050c16b3afda0e05a5e1cd53db8ab6e6847676/build.gradle#L39

**Comment by gavlyukovskiy** [comment]
Hi, I started working to migrate to brave instrumentation, but I'm not sure when it will be finished. There is some code in branch `brave`, but I'm not sure about it stability, since it's not well tested yet. 
If you have courage to help with testing it on real application, you're welcome to build it from sources and give it a try, I will gladly help you if you have any questions or if you need me to build artifact for you.

**Comment by shakuzen** [comment]
If a snapshot version is made available somewhere, it would be easiest for me (and others) to test it. I tried to run a build of the `brave` branch (`./gradlew build`) but it fails to compile due to Brave not being on the classpath.

**Comment by gavlyukovskiy** [comment]
This is really strange, I'll try to publish snapshots somewhere to oss.jfrog.org as soon as I can, I'm waiting for my request to be completed.

**Comment by gavlyukovskiy** [comment]
I've just released version 1.5.0 that supports Finchley. Please try it out!
