### ISSUE TITLE
DatasourceProxy is no longer working in Version 1.9.0 with Spring Boot 2.6

### ISSUE THREAD

**Issue by flpa** [gavlyukovskiy/spring-boot-data-source-decorator#83]
Hey,
I'm using Spring Boot 2.6.14 in a project and noticed that the autoconfiguration for datasource-proxy is no longer working when I upgrade to lib version 1.9.0.

My setup is like in the manual - I included "datasource-proxy-spring-boot-starter" in my pom and enabled the Decorator + Query Logging. I've switched back and forth between 1.8.1 and 1.9.0 to confirm - in 1.8.1, query logging and counting is working, in 1.9.0 it is not, with the exact same setup.

Did I miss any migration steps from 1.8.1 to 1.9.0, or is only Spring Boot 3 supported from now on?
For now I'll stay on 1.8.1.

**Comment by gavlyukovskiy** [comment]
1.9.0 version uses new auto-configuration mechanism added in 2.7, old one was removed in 3.0, so we had to make this change. If you're using 2.6 feel free to stay on 1.8.1, there are no other changes between the versions. And if something critical pops up I can always backcourt it to 1.8.2.

**Comment by scordio** [comment]
Hi @gavlyukovskiy, being 1.9.0 a minor version upgrade, it's not obvious that there is a breaking change caused by the underlying upgrade of Spring Boot.

Would you consider releasing the 1.9.0 content as 2.0.0 and also the 1.8.1 content as 1.9.1?

This way, the 1.x line would stay compatible with Spring Boot 2, while 2.x would follow Spring Boot 3.
