### ISSUE TITLE
Tracing not working post upgrading to Springboot 3

### ISSUE THREAD

**Issue by navaneeth-spotnana** [gavlyukovskiy/spring-boot-data-source-decorator#86]
After upgrading to SpringBoot 3, we moved to using micrometer-tracing with brave as the tracer. DB call spans disappeared from trace, and I had to add `io.zipkin.brave:brave-instrumentation-p6spy` as dependency and add spy.properties file with `modulelist=brave.p6spy.TracingP6Factory` as content for tracing to work.

Is this expected, or am I missing some configuration in spring-boot-data-source-decorator?

**Comment by gavlyukovskiy** [comment]
Well, tracing specifically has been moved to sleuth project quite some time ago and since then sleuth itself was semi-deprecated. haven't looked much into micrometer-tracing, but I know that https://github.com/jdbc-observations/datasource-micrometer project is using adapted version of this library to provide tracing through datasource-proxy (practically not different from p6spy).

**Comment by navaneeth-spotnana** [comment]
Thank you, we have moved to [datasource-micrometer](https://github.com/jdbc-observations/datasource-micrometer) few weeks ago and things are working fine.
